var lnx_preload = {
	
	folder : "./images/",
	
	images : [
	"1_1_1.jpg",
	"1_2_1.jpg",
	"1_3_1.jpg",
	"2_1_1.jpg",
	"2_2_1.jpg",
	"3_1_1.jpg",
	"3_2_1_2.jpg",
	"3_2_1_3.jpg",
	"3_2_1.jpg",
	"3_3_1_2.jpg",
	"3_3_1_3.jpg",
	"3_3_1_4.jpg",
	"3_3_1.jpg",
	"3_4_1_2.jpg",
	"3_4_1_3.jpg",
	"3_4_1_4.jpg",
	"3_4_1.jpg",
	"3_5_1_2.jpg",
	"3_5_1_3.jpg",
	"3_5_1_4.jpg",
	"3_5_1_5.jpg",
	"3_5_1_6.jpg",
	"3_5_1_7.jpg",
	"3_5_1.jpg",
	"3_6_1_2.jpg",
	"3_6_1_3.jpg",
	"3_6_1_4.jpg",
	"3_6_1.jpg",
	"3_7_1_10.jpg",
	"3_7_1_11.jpg",
	"3_7_1_2.jpg",
	"3_7_1_3.jpg",
	"3_7_1_4.jpg",
	"3_7_1_5.jpg",
	"3_7_1_6.jpg",
	"3_7_1_7.jpg",
	"3_7_1_8.jpg",
	"3_7_1_9.jpg",
	"3_7_1.jpg",
	"audio_off.svg",
	"audio_on.svg",
	"back.svg",
	"backDisabled.svg",
	"blueComplete.svg",
	"close.png",
	"close.svg",
	"confirmIcon.png",
	"exit.svg",
	"fc_0.jpg",
	"fc_cyan.jpg",
	"fc_green.jpg",
	"fc_magenta.jpg",
	"fc_purple.jpg",
	"fc_yellow.jpg",
	"fcBack.svg",
	"fcFwd.svg",
	"fwd.svg",
	"fwdDisabled.svg",
	"greenComplete.svg",
	"Icon_Active Wheelchair_Large_White.png",
	"Icon_Caring Heart_Large_White.png",
	"Icon_CEC_Large_White.png",
	"Icon_Chat_Large_White.png",
	"Icon_Collaboration_Large_White.png",
	"Icon_Do Not Touch_Large_White.png",
	"Icon_Employee Relations_Large_White.png",
	"Icon_Evalution_Large_White.png",
	"Icon_Family V3 Full Body_Large_White.png",
	"Icon_Food Label_Large_White.png",
	"Icon_Government_Large_White.png",
	"Icon_Healthcare Workers_Large_White.png",
	"Icon_In Person Meeting_Large_White_v2.png",
	"Icon_Justice_Large_White.png",
	"Icon_Libre View_Large_White.png",
	"Icon_Nutrition Products V2_Large_White.png",
	"Icon_Partnership Giving_Large_White.png",
	"Icon_Partnership_Large_White.png",
	"Icon_Patient Interaction_Large_White.png",
	"Icon_Plate_Large_White.png",
	"Icon_Regulatory Compliance_Large_White.png",
	"Icon_Reprocessing_Large_White.png",
	"Icon_Research Science_Large_White.png",
	"Icon_Sensor Wear_Large_White.png",
	"Icon_Smart Phone V1_Large_White.png",
	"Icon_Speaker_Large_White.png",
	"Icon_Travel_Large_White.png",
	"knowledgecheck_cross.gif",
	"knowledgecheck_tick.gif",
	"learnHowBg.png",
	"lockClosed.svg",
	"lockOpen.svg",
	"lockOpenClosed.svg",
	"logo.svg",
	"modIcon.png",
	"popup_close.png",
	"prog.svg",
	"qcCheck.png",
	"qcQuesImg.png",
	"qcX.png",
	"ref.svg",
	"resources_icon_legal_up.gif",
	"resources_icon_manager_up.gif",
	"resources_icon_online_up.gif",
	"resources_icon_pdf_up.gif",
	"resources_icon_phone_up.gif",
	"rightAngle.svg",
	"texSecBg.svg",
	"toc.svg",
	"tocClose.svg",
	"whiteComplete.svg"
	],
	//images : [],
	
	run : function(){
		
		for( var i = 0, len = this.images.length; i < len; i++ ){

			var img = (new Image()).src = this.folder + this.images[i];
		}
	}
};
